@startuml

actor "Natural Person" as person
participant  "xShare Yellow Button Provider"  as xShare #d7d30d
participant "xShare Yellow Button Consumer" as Recipient  #d7d30d
database "Natural person's Storage" as Storage

==== Natural person authentication (pre-condition) ====
group "Natural person IAA" [[#natural-person-authentication Natural person authentication]]
end group

==== Search and Select Health Data ====
group Search and Select personal health data [[#search-and-select Search and Select]]
end group

==== Retrieve and Format Health Data ====
group Retrieve and Format Natural personal health data [[#retrieve-and-format Retrieve and Format]]
end group

==== Selects Options ====
opt 
group Select options [[#select-options Select Options]]
end group
end opt

==== Yellow Button Options ====

opt 
group Download
person -> xShare: download
xShare -[#blue]> Storage: <color:blue> [ [[ #download download ]] ]
deactivate xShare
end group
end opt

opt 
group One-time Share and Linked Options
person -> xShare: generate link
activate xShare

opt
group One-time Share
xShare -[#blue]> xShare: <color:blue> [ [[ #generate-shl-uri generate SHL URI]] ]
end group
end opt
opt
group Linked Options
xShare -> xShare: <color:blue> [ [[ #generate-shl-uri SHL generated]\n (flag set to L: long-term; exp specified)]] ]
end group
end opt
return show link
person -> Recipient: share link
activate Recipient
Recipient -[#blue]> Recipient:  <color:blue> [ [[ #process-shl-uri process SHL URI]] ]
Recipient -[#blue]> xShare:  <color:blue> [ [[#request-shl-manifest request SHL Manifest]] ]
activate xShare
return <color:blue> health data
deactivate Recipient
end group
end opt


@enduml